consul:
  hostname: consul
  image: linyows/consul:1.2-server
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  ports:
    - '10053:53/tcp'
    - '10053:53/udp'
    - '8500:8500'
vault:
  build: ./vault
  environment:
    VAULT_REDIRECT_ADDR: https://vault.service.consul:8200
  ports:
    - '8200-8201:8200'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
mysql:
  hostname: mysql
  build: ./mysql
  environment:
    MYSQL_DATABASE: express
  ports:
    - '13306:3306'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
express:
  hostname: express
  build: ./express
  environment:
    VAULT_ADDR: https://vault.service.consul:8200
    DB_HOST: mysql.node.consul
    DB_PORT: '3306'
  ports:
    - '3000:3000'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
